# Generated by Django 3.2.8 on 2021-11-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='desirable_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='masters_cutoff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Masters CGPA cutoff'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('NS', 'Not started'), ('AO', 'Applications open'), ('IP', 'In progress'), ('CO', 'Completed'), ('CL', 'Closed')], max_length=2, verbose_name='Status'),
        ),
    ]
