# Generated by Django 3.2.8 on 2021-10-29 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applied_by',
            field=models.ManyToManyField(related_name='applied_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='num_of_students_applied',
            field=models.IntegerField(default=0),
        ),
    ]
