# Generated by Django 3.2.8 on 2021-10-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='files',
        ),
    ]
