# Generated by Django 3.2.8 on 2021-10-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_remove_job_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobalert',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='backlogs_history',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='technical_skills',
            field=models.TextField(default='null', verbose_name='Technical Skills'),
            preserve_default=False,
        ),
    ]
