# Generated by Django 3.2.8 on 2021-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20211116_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogsAndEducationGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backlogs_status', models.CharField(default='NB', max_length=3)),
                ('backlogs_cleared', models.SmallIntegerField(blank=True, null=True)),
                ('outstanding_backlogs', models.SmallIntegerField(blank=True, null=True)),
                ('backlogs_history', models.TextField(blank=True, null=True)),
                ('gap_in_education', models.BooleanField()),
                ('reason_for_gap_in_education', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Awards/Recognitions received')),
                ('publications', models.TextField(blank=True, null=True, verbose_name='Papers published')),
                ('hackathons_participated', models.TextField(blank=True, null=True, verbose_name='Hackathons Participated')),
                ('extra_curricular_activities', models.TextField(blank=True, null=True, verbose_name='Extra Curricular Activities')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.TextField(verbose_name='Technical Skills')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='backlogs_cleared',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='backlogs_history',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='backlogs_status',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='extra_curricular_activities',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='gap_in_education',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='hackathons_participated',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='outstanding_backlogs',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='reason_for_gap_in_education',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='technical_skills',
        ),
    ]
