# Generated by Django 3.2.8 on 2021-11-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_auto_20211031_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Certification name'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='area',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_team_project',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Project title'),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Name of the site. Like GitHub, LinkedIn etc.'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Awards/Recognitions received'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='backlogs_cleared',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='backlogs_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='extra_curricular_activities',
            field=models.TextField(blank=True, null=True, verbose_name='Extra Curricular Activities'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='hackathons_participated',
            field=models.TextField(blank=True, null=True, verbose_name='Hackathons Participated'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='outstanding_backlogs',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='publications',
            field=models.TextField(blank=True, null=True, verbose_name='Papers published'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='reason_for_gap_in_education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
